### ISSUE TITLE
PATCH 錯誤訊息

### ISSUE THREAD

**Issue by ManiYang** [z6wdc/todolistTeam#15]
測試 PATCH 的時候，API 回覆下列訊息：
```
{
  "status": false,
  "message": "Todo.findIndex is not a function"
}
```

**Comment by ManiYang** [comment]
https://github.com/z6wdc/todolistTeam/blob/6564b4999623234c0ca942bf9952fefe8de37d11/patchTodo.js#L5-L9

第 9 行：`Todo` 應該沒有叫做 `findIndex()` 的 method

**Comment by ManiYang** [comment]
https://github.com/z6wdc/todolistTeam/blob/6564b4999623234c0ca942bf9952fefe8de37d11/patchTodo.js#L5-L22

1. 第 7 行：建議將變數 `todo` 改名為 `title`，因為這裡已經取出 title 的值
1. 第 9 行：可以不用在這裡檢查傳入的 `id` 是否存在，從 `findByIdAndUpdate()` (第 13 行) 的回傳值 (`result`) 判斷即可，如果回傳 `null` 代表找不到。(此外， `Todo` 沒有叫做 `findIndex` 的 method)
1. 第 13 行：`findByIdAndUpdate()` 第 2 個參數應代入一個 object
2. 可在 14 行前加上
  ```js
  if (result === null) 
    throw new Error("找不到指定 id 的 todo");  
  ```

**Comment by wting04** [comment]
謝謝幫忙測試，我有重新推分支上來了~
